LR08/LR08/apps/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/leave_comment/', views.leave_comment, name='leave_comment')
]

LR08/LR08/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('articles/', include('articles.urls')),
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
]

LR08/LR08/apps/articles/models.py
import datetime
from django.db import models
from django.utils import timezone


class Article(models.Model):
    article_title = models.CharField('Название статьи', max_length=200)
    article_text = models.TextField('Текст статьи')
    pub_date = models.DateField('Дата публикации')

    def __str__(self):
        return self.article_title

    def was_published_resently(self):
        return self.pub_date >= timezone.localdate() - timezone.timedelta(days=7)

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('Имя автора', max_length=50)
    comment_text = models.CharField('Текст комментария', max_length=200)

    def __str__(self):
        return self.author_name

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

LR08/LR08/apps/articles/views.py
from django.shortcuts import render
from .models import Article
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse

def index(request):
    latest_articles_list = Article.objects.order_by('-pub_date')[:5]
    return render(request, 'articles/list.html', {'latest_articles_list': latest_articles_list})


def detail(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404('Статья не найдена')

    latest_comments_list = a.comment_set.order_by('-id')[:10]

    return render(request, 'articles/detail.html', {'article': a, 'latest_comments_list': latest_comments_list})


def leave_comment(request, article_id):
    try:
        a = Article.objects.get(id=article_id)
    except:
        raise Http404('Статья не найдена')

    a.comment_set.create(
        author_name=request.POST['name'], comment_text=request.POST['text'])

    return HttpResponseRedirect(reverse('articles:detail', args=(a.id,)))

LR08/LR08/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}{{article.article_title}}{% endblock %}

{% block content %}

<h2>{{article.article_title}}</h2>
<p>{{article.article_text}}</p>
<em>{{article.pub_date}}</em>

{% if article.was_published_resently %}
Новая статья
{% endif %}

<hr>

{% if latest_comments_list %}

    {% for c in latest_comments_list %}
        <p>
            <strong>{{c.author_name}}</strong>
            <p>{{c.comment_text}}</p>
        </p>
    {% endfor %}

{% else %}
Комменты не найдены
{% endif %}

<hr>

<form action="{% url 'articles:leave_comment' article.id %}" method="POST">

    {% csrf_token %}

    <input type="text" required placeholder="Ваше имя" name="name"><br>
    <textarea name="text" required="" placeholder="Текст комментария" cols="30" rows="10"></textarea><br>

    <button type="submit">Оставить комментарий</button>

</form>

{% endblock %}

LR08/LR08/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}Последние статьи{% endblock %}

{% block content %}

  {% if latest_articles_list %}

      {% for a in  latest_articles_list %}
          <a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a>
      {% endfor %}

  {% else %}
    Статьи не найдены :(
  {% endif %}

{% endblock %}

LR08/LR08/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Мой сайт{% endblock %}</title>
</head>
<body>

{% block content %}{% endblock %}

</body>
</html>